
var createFFmpegCore = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmpegCore) {
  createFFmpegCore = createFFmpegCore || {};


var f;f||(f=typeof createFFmpegCore !== 'undefined' ? createFFmpegCore : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});f.quit=function(a){if(f.onExit)f.onExit(a);throw new ca(a);};f.exit=da;ea=h=function(){};var fa={},ia;for(ia in f)f.hasOwnProperty(ia)&&(fa[ia]=f[ia]);var ja=[],ka="./this.program";function la(a,b){throw b;}var ma=!1,oa=!1,l=!1,pa=!1;ma="object"===typeof window;oa="function"===typeof importScripts;
l="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;pa=!ma&&!l&&!oa;var n=f.ENVIRONMENT_IS_PTHREAD||!1;n&&(qa=f.buffer);var ra="";function sa(a){return f.locateFile?f.locateFile(a,ra):ra+a}var ta,va,wa,xa;
if(l){ra=oa?require("path").dirname(ra)+"/":__dirname+"/";ta=function(a,b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")};va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ka=process.argv[1].replace(/\\/g,"/"));ja=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ca))throw a;});process.on("unhandledRejection",u);la=function(a){process.exit(a)};f.inspect=
function(){return"[Emscripten Module object]"};var ya;try{ya=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=ya.Worker}else if(pa)"undefined"!=typeof read&&(ta=function(a){return read(a)}),va=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ja=scriptArgs:
"undefined"!=typeof arguments&&(ja=arguments),"function"===typeof quit&&(la=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ma||oa)oa?ra=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ra=document.currentScript.src),_scriptDir&&(ra=_scriptDir),0!==ra.indexOf("blob:")?ra=ra.substr(0,ra.lastIndexOf("/")+1):ra="",l?(ta=function(a,
b){wa||(wa=require("fs"));xa||(xa=require("path"));a=xa.normalize(a);return wa.readFileSync(a,b?null:"utf8")},va=function(a){a=ta(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(ta=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},oa&&(va=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));l&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);
var ea=f.print||console.log.bind(console),h=f.printErr||console.warn.bind(console);for(ia in fa)fa.hasOwnProperty(ia)&&(f[ia]=fa[ia]);fa=null;f.arguments&&(ja=f.arguments);f.thisProgram&&(ka=f.thisProgram);f.quit&&(la=f.quit);var za,Aa=0,Ba;f.wasmBinary&&(Ba=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&u("no native wasm support detected");var Ca,Da,threadInfoStruct=0,selfThreadId=0,Ea=!1;
function assert(a,b){a||u("Assertion failed: "+b)}function Fa(a){var b=f["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function Ga(a,b,c,d){var e={string:function(q){var t=0;if(null!==q&&void 0!==q&&0!==q){var w=(q.length<<2)+1;t=Ha(w);Ia(q,t,w)}return t},array:function(q){var t=Ha(q.length);v.set(q,t);return t}},g=Fa(a),k=[];a=0;if(d)for(var m=0;m<d.length;m++){var r=e[c[m]];r?(0===a&&(a=y()),k[m]=r(d[m])):k[m]=d[m]}c=g.apply(null,k);c="string"===b?A(c):"boolean"===b?!!c:c;0!==a&&C(a);return c}
function Ja(a,b,c){c=b+c;for(var d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function A(a,b){return a?Ja(Ka,a,b):""}
function La(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}function Ia(a,b,c){return La(a,Ka,b,c)}
function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Na(a){var b=Ma(a)+1,c=Oa(b);c&&La(a,v,c,b);return c}function Pa(a){var b=Ma(a)+1,c=Ha(b);La(a,v,c,b);return c}function Ra(a,b,c){for(var d=0;d<a.length;++d)v[b++>>0]=a.charCodeAt(d);c||(v[b>>0]=0)}var qa,v,Ka,Sa,Ta,D,E,F,Ua,Va=f.INITIAL_MEMORY||1073741824;
if(n)Ca=f.wasmMemory,qa=f.buffer;else if(f.wasmMemory)Ca=f.wasmMemory;else if(Ca=new WebAssembly.Memory({initial:Va/65536,maximum:Va/65536,shared:!0}),!(Ca.buffer instanceof SharedArrayBuffer))throw h("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),l&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");Ca&&(qa=Ca.buffer);Va=qa.byteLength;var Wa=qa;qa=Wa;f.HEAP8=v=new Int8Array(Wa);f.HEAP16=Sa=new Int16Array(Wa);f.HEAP32=D=new Int32Array(Wa);f.HEAPU8=Ka=new Uint8Array(Wa);f.HEAPU16=Ta=new Uint16Array(Wa);f.HEAPU32=E=new Uint32Array(Wa);f.HEAPF32=F=new Float32Array(Wa);f.HEAPF64=Ua=new Float64Array(Wa);var G,Xa=[],Ya=[],Za=[],$a=[],ab=[];function bb(){var a=f.preRun.shift();Xa.unshift(a)}var cb=0,db=null,eb=null;
function gb(){assert(!n,"addRunDependency cannot be used in a pthread worker");cb++;f.monitorRunDependencies&&f.monitorRunDependencies(cb)}function hb(){cb--;f.monitorRunDependencies&&f.monitorRunDependencies(cb);if(0==cb&&(null!==db&&(clearInterval(db),db=null),eb)){var a=eb;eb=null;a()}}f.preloadedImages={};f.preloadedAudios={};
function u(a){if(f.onAbort)f.onAbort(a);n&&console.error("Pthread aborting at "+Error().stack);h(a);Ea=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function ib(a){var b=jb;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function kb(){return ib("data:application/octet-stream;base64,")}var jb="ffmpeg-core.wasm";kb()||(jb=sa(jb));
function lb(){try{if(Ba)return new Uint8Array(Ba);if(va)return va(jb);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}function mb(){return Ba||!ma&&!oa||"function"!==typeof fetch||ib("file://")?Promise.resolve().then(lb):fetch(jb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+jb+"'";return a.arrayBuffer()}).catch(function(){return lb()})}
var H,J,ob={5449136:function(){throw"Canceled!";},5449356:function(a,b){setTimeout(function(){nb(a,b)},0)},5449458:function(){return 5242880}};function pb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.vh;"number"===typeof c?void 0===b.Tf?G.get(c)():G.get(c)(b.Tf):c(void 0===b.Tf?null:b.Tf)}}}function qb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}
f.dynCall=function(a,b,c){var d;-1!=a.indexOf("j")?d=c&&c.length?f["dynCall_"+a].apply(null,[b].concat(c)):f["dynCall_"+a].call(null,b):d=G.get(b).apply(null,c);return d};var rb=0,sb=0,tb=0;function ub(a,b,c){rb=a|0;tb=b|0;sb=c|0}f.registerPthreadPtr=ub;
function vb(a,b){if(0>=a||a>v.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(D,L.Vf>>2),d=0;if(c==a&&Atomics.compareExchange(D,L.Vf>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(D,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}f._emscripten_futex_wake=vb;
function wb(a){if(n)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cancelThread!";L.Ef[a].worker.postMessage({cmd:"cancel"})}function xb(a){if(n)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";D[a+12>>2]=0;(a=L.Ef[a])&&L.Ag(a.worker)}
var L={Ph:1,nj:{Ih:0,Jh:0},Gf:[],Kf:[],lj:function(){},pi:function(){L.xf=Oa(232);for(var a=0;58>a;++a)E[L.xf/4+a]=0;D[L.xf+12>>2]=L.xf;a=L.xf+156;D[a>>2]=a;var b=Oa(512);for(a=0;128>a;++a)E[b/4+a]=0;Atomics.store(E,L.xf+104>>2,b);Atomics.store(E,L.xf+40>>2,L.xf);Atomics.store(E,L.xf+44>>2,42);L.Ch();ub(L.xf,!oa,1);yb(L.xf)},ri:function(){L.Ch();aa(f);L.receiveObjectTransfer=L.Ii;L.setThreadStatus=L.Li;L.threadCancel=L.Pi;L.threadExit=L.Qi},Ch:function(){L.Vf=zb},Ef:{},Dg:[],Li:function(){},eh:function(){for(;0<
L.Dg.length;)L.Dg.pop()();n&&threadInfoStruct&&Ab()},Qi:function(a){var b=rb|0;b&&(Atomics.store(E,b+4>>2,a),Atomics.store(E,b+0>>2,1),Atomics.store(E,b+60>>2,1),Atomics.store(E,b+64>>2,0),L.eh(),vb(b+0,2147483647),ub(0,0,0),threadInfoStruct=0,n&&postMessage({cmd:"exit"}))},Pi:function(){L.eh();Atomics.store(E,threadInfoStruct+4>>2,-1);Atomics.store(E,threadInfoStruct+0>>2,1);vb(threadInfoStruct+0,2147483647);threadInfoStruct=selfThreadId=0;ub(0,0,0);postMessage({cmd:"cancelDone"})},Oi:function(){for(var a in L.Ef){var b=
L.Ef[a];b&&b.worker&&L.Ag(b.worker)}L.Ef={};for(a=0;a<L.Gf.length;++a){var c=L.Gf[a];c.terminate()}L.Gf=[];for(a=0;a<L.Kf.length;++a)c=L.Kf[a],b=c.yf,L.Pg(b),c.terminate();L.Kf=[]},Pg:function(a){if(a){if(a.threadInfoStruct){var b=D[a.threadInfoStruct+104>>2];D[a.threadInfoStruct+104>>2]=0;Bb(b);Bb(a.threadInfoStruct)}a.threadInfoStruct=0;a.Kg&&a.Rf&&Bb(a.Rf);a.Rf=0;a.worker&&(a.worker.yf=null)}},Ag:function(a){delete L.Ef[a.yf.Lh];L.Gf.push(a);L.Kf.splice(L.Kf.indexOf(a),1);L.Pg(a.yf);a.yf=void 0},
Ii:function(){},vi:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.yf&&(L.Mg=a.yf.threadInfoStruct);if(d.targetThread&&d.targetThread!=(rb|0)){var g=L.Ef[d.xj];g?g.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Cb();else if("spawnThread"===e)Db(c.data);else if("cleanupThread"===e)xb(d.thread);else if("killThread"===
e){c=d.thread;if(n)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";D[c+12>>2]=0;c=L.Ef[c];c.worker.terminate();L.Pg(c);L.Kf.splice(L.Kf.indexOf(c.worker),1);c.worker.yf=void 0}else if("cancelThread"===e)wb(d.thread);else if("loaded"===e)a.loaded=!0,b&&b(a),a.og&&(a.og(),delete a.og);else if("print"===e)ea("Thread "+d.threadId+": "+d.text);else if("printErr"===e)h("Thread "+d.threadId+": "+d.text);
else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===e)a.yf&&Atomics.load(E,a.yf.Lh+68>>2)&&L.Ag(a);else if("exitProcess"===e){noExitRuntime=!1;try{da(d.returnCode)}catch(k){if(k instanceof ca)return;throw k;}}else"cancelDone"===e?L.Ag(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):h("worker sent an unknown command "+e));L.Mg=void 0};a.onerror=function(c){h("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};l&&(a.on("message",
function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:f.mainScriptUrlOrBlob||_scriptDir,wasmMemory:Ca,wasmModule:Da})},Vh:function(){var a=sa("ffmpeg-core.worker.js");L.Gf.push(new Worker(a))},li:function(){0==L.Gf.length&&(L.Vh(),L.vi(L.Gf[0]));return 0<L.Gf.length?L.Gf.pop():null},Zi:function(a){for(a=performance.now()+a;performance.now()<a;);}};f.establishStackSpace=function(a){C(a)};f.getNoExitRuntime=function(){return noExitRuntime};
var Eb;l?Eb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:n?Eb=function(){return performance.now()-f.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Eb=dateNow:Eb=function(){return performance.now()};function Fb(a){return D[Gb()>>2]=a}function Hb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Eb();else return Fb(28),-1;D[b>>2]=a/1E3|0;D[b+4>>2]=a%1E3*1E6|0;return 0}function Ib(a,b){if(n)return M(1,1,a,b);$a.unshift({vh:a,Tf:b})}
function Jb(a,b){a=new Date(1E3*D[a>>2]);D[b>>2]=a.getUTCSeconds();D[b+4>>2]=a.getUTCMinutes();D[b+8>>2]=a.getUTCHours();D[b+12>>2]=a.getUTCDate();D[b+16>>2]=a.getUTCMonth();D[b+20>>2]=a.getUTCFullYear()-1900;D[b+24>>2]=a.getUTCDay();D[b+36>>2]=0;D[b+32>>2]=0;D[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;Jb.ih||(Jb.ih=Na("GMT"));D[b+40>>2]=Jb.ih;return b}
function Kb(){function a(k){return(k=k.toTimeString().match(/\(([A-Za-z ]+)\)$/))?k[1]:"GMT"}if(n)return M(2,1);if(!Kb.Yh){Kb.Yh=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),g=Math.max(b,e);D[Lb()>>2]=60*g;D[Mb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Na(c);d=Na(d);e<b?(D[Nb()>>2]=c,D[Nb()+4>>2]=d):(D[Nb()>>2]=d,D[Nb()+4>>2]=c)}}
function Ob(a,b){Kb();a=new Date(1E3*D[a>>2]);D[b>>2]=a.getSeconds();D[b+4>>2]=a.getMinutes();D[b+8>>2]=a.getHours();D[b+12>>2]=a.getDate();D[b+16>>2]=a.getMonth();D[b+20>>2]=a.getFullYear()-1900;D[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);D[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;D[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;D[b+32>>2]=a;a=D[Nb()+(a?4:0)>>2];
D[b+40>>2]=a;return b}function Pb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Qb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Pb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Rb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Sb(a){if("/"===a)return"/";a=Qb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function Tb(a,b){return Qb(a+"/"+b)}
function Ub(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(l)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){u("randomDevice")}}
function Vb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:N.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Pb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Wb(a,b){function c(k){for(var m=0;m<k.length&&""===k[m];m++);for(var r=k.length-1;0<=r&&""===k[r];r--);return m>r?[]:k.slice(m,r-m+1)}a=Vb(a).substr(1);b=Vb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")}var Xb=[];function Yb(a,b){Xb[a]={input:[],output:[],Yf:b};N.dh(a,Zb)}
var Zb={open:function(a){var b=Xb[a.node.rdev];if(!b)throw new N.af(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Yf.flush(a.tty)},flush:function(a){a.tty.Yf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Yf.xh)throw new N.af(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Yf.xh(a.tty)}catch(m){throw new N.af(29);}if(void 0===k&&0===e)throw new N.af(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Yf.Zg)throw new N.af(60);
try{for(var e=0;e<d;e++)a.tty.Yf.Zg(a.tty,b[c+e])}catch(g){throw new N.af(29);}d&&(a.node.timestamp=Date.now());return e}},ac={xh:function(a){if(!a.input.length){var b=null;if(l){var c=Buffer.Sf?Buffer.Sf(256):new Buffer(256),d=0;try{d=wa.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=$b(b,!0)}return a.input.shift()},Zg:function(a,b){null===b||10===b?(ea(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ea(Ja(a.output,0)),a.output=[])}},ec={Zg:function(a,b){null===b||10===b?(h(Ja(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Ja(a.output,0)),a.output=[])}},O={Df:null,jf:function(){return O.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(N.si(c)||N.isFIFO(c))throw new N.af(63);O.Df||(O.Df={dir:{node:{Af:O.cf.Af,nf:O.cf.nf,lookup:O.cf.lookup,Ff:O.cf.Ff,rename:O.cf.rename,unlink:O.cf.unlink,rmdir:O.cf.rmdir,readdir:O.cf.readdir,symlink:O.cf.symlink},stream:{tf:O.df.tf}},file:{node:{Af:O.cf.Af,nf:O.cf.nf},stream:{tf:O.df.tf,read:O.df.read,write:O.df.write,fg:O.df.fg,Wf:O.df.Wf,Xf:O.df.Xf}},link:{node:{Af:O.cf.Af,nf:O.cf.nf,readlink:O.cf.readlink},stream:{}},lh:{node:{Af:O.cf.Af,nf:O.cf.nf},
stream:N.$h}});c=N.createNode(a,b,c,d);N.kf(c.mode)?(c.cf=O.Df.dir.node,c.df=O.Df.dir.stream,c.bf={}):N.isFile(c.mode)?(c.cf=O.Df.file.node,c.df=O.Df.file.stream,c.gf=0,c.bf=null):N.Mf(c.mode)?(c.cf=O.Df.link.node,c.df=O.Df.link.stream):N.hg(c.mode)&&(c.cf=O.Df.lh.node,c.df=O.Df.lh.stream);c.timestamp=Date.now();a&&(a.bf[b]=c);return c},gj:function(a){if(a.bf&&a.bf.subarray){for(var b=[],c=0;c<a.gf;++c)b.push(a.bf[c]);return b}return a.bf},hj:function(a){return a.bf?a.bf.subarray?a.bf.subarray(0,
a.gf):new Uint8Array(a.bf):new Uint8Array(0)},sh:function(a,b){var c=a.bf?a.bf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.bf,a.bf=new Uint8Array(b),0<a.gf&&a.bf.set(c.subarray(0,a.gf),0))},Ji:function(a,b){if(a.gf!=b)if(0==b)a.bf=null,a.gf=0;else{if(!a.bf||a.bf.subarray){var c=a.bf;a.bf=new Uint8Array(b);c&&a.bf.set(c.subarray(0,Math.min(b,a.gf)))}else if(a.bf||(a.bf=[]),a.bf.length>b)a.bf.length=b;else for(;a.bf.length<b;)a.bf.push(0);a.gf=b}},cf:{Af:function(a){var b=
{};b.dev=N.hg(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N.kf(a.mode)?b.size=4096:N.isFile(a.mode)?b.size=a.gf:N.Mf(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Xh=4096;b.blocks=Math.ceil(b.size/b.Xh);return b},nf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Ji(a,b.size)},lookup:function(){throw N.Qg[44];},Ff:function(a,
b,c,d){return O.createNode(a,b,c,d)},rename:function(a,b,c){if(N.kf(a.mode)){try{var d=N.Bf(b,c)}catch(g){}if(d)for(var e in d.bf)throw new N.af(55);}delete a.parent.bf[a.name];a.name=c;b.bf[c]=a;a.parent=b},unlink:function(a,b){delete a.bf[b]},rmdir:function(a,b){var c=N.Bf(a,b),d;for(d in c.bf)throw new N.af(55);delete a.bf[b]},readdir:function(a){var b=[".",".."],c;for(c in a.bf)a.bf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!N.Mf(a.mode))throw new N.af(28);
return a.link}},df:{read:function(a,b,c,d,e){var g=a.node.bf;if(e>=a.node.gf)return 0;a=Math.min(a.node.gf-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.bf||a.bf.subarray)){if(g)return a.bf=b.subarray(c,c+d),a.gf=d;if(0===a.gf&&0===e)return a.bf=b.slice(c,c+d),a.gf=d;if(e+d<=a.gf)return a.bf.set(b.subarray(c,c+d),e),d}O.sh(a,e+d);if(a.bf.subarray&&b.subarray)a.bf.set(b.subarray(c,
c+d),e);else for(g=0;g<d;g++)a.bf[e+g]=b[c+g];a.gf=Math.max(a.gf,e+d);return d},tf:function(a,b,c){1===c?b+=a.position:2===c&&N.isFile(a.node.mode)&&(b+=a.node.gf);if(0>b)throw new N.af(28);return b},fg:function(a,b,c){O.sh(a.node,b+c);a.node.gf=Math.max(a.node.gf,b+c)},Wf:function(a,b,c,d,e,g){assert(0===b);if(!N.isFile(a.node.mode))throw new N.af(43);a=a.node.bf;if(g&2||a.buffer!==qa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/
16384);for(b=Oa(g);c<g;)v[b+c++]=0;c=b;if(!c)throw new N.af(48);v.set(a,c)}else d=!1,c=a.byteOffset;return{Hi:c,Jg:d}},Xf:function(a,b,c,d,e){if(!N.isFile(a.node.mode))throw new N.af(43);if(e&2)return 0;O.df.write(a,b,0,d,c,!1);return 0}}},N={root:null,mg:[],ph:{},streams:[],Ai:1,Cf:null,oh:"/",Tg:!1,Bh:!0,mf:{},Mh:{Gh:{Rh:1,Sh:2}},af:null,Qg:{},ii:null,Cg:0,kj:function(a){if(!(a instanceof N.af)){a:{var b=Error();if(!b.stack){try{throw Error();}catch(c){b=c}if(!b.stack){b="(no stack trace available)";
break a}}b=b.stack.toString()}f.extraStackTrace&&(b+="\n"+f.extraStackTrace());b=qb(b);throw a+" : "+b;}return Fb(a.ef)},ff:function(a,b){a=Vb(N.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Og:!0,ah:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ah)throw new N.af(32);a=Pb(a.split("/").filter(function(k){return!!k}),!1);var e=N.root;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=N.Bf(e,a[d]);c=Tb(c,a[d]);N.Nf(e)&&(!g||g&&b.Og)&&(e=e.lg.root);if(!g||b.wf)for(g=
0;N.Mf(e.mode);)if(e=N.readlink(c),c=Vb(Rb(c),e),e=N.ff(c,{ah:b.ah}).node,40<g++)throw new N.af(32);}return{path:c,node:e}},If:function(a){for(var b;;){if(N.wg(a))return a=a.jf.Eh,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Sg:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.Cf.length},zh:function(a){var b=N.Sg(a.parent.id,a.name);a.Pf=N.Cf[b];N.Cf[b]=a},Ah:function(a){var b=N.Sg(a.parent.id,a.name);if(N.Cf[b]===a)N.Cf[b]=a.Pf;
else for(b=N.Cf[b];b;){if(b.Pf===a){b.Pf=a.Pf;break}b=b.Pf}},Bf:function(a,b){var c=N.yi(a);if(c)throw new N.af(c,a);for(c=N.Cf[N.Sg(a.id,b)];c;c=c.Pf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return N.lookup(a,b)},createNode:function(a,b,c,d){a=new N.Oh(a,b,c,d);N.zh(a);return a},Ng:function(a){N.Ah(a)},wg:function(a){return a===a.parent},Nf:function(a){return!!a.lg},isFile:function(a){return 32768===(a&61440)},kf:function(a){return 16384===(a&61440)},Mf:function(a){return 40960===(a&61440)},
hg:function(a){return 8192===(a&61440)},si:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},ji:{r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218},Dh:function(a){var b=N.ji[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},th:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Jf:function(a,b){if(N.Bh)return 0;
if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0},yi:function(a){var b=N.Jf(a,"x");return b?b:a.cf.lookup?0:2},Yg:function(a,b){try{return N.Bf(a,b),20}catch(c){}return N.Jf(a,"wx")},xg:function(a,b,c){try{var d=N.Bf(a,b)}catch(e){return e.ef}if(a=N.Jf(a,"wx"))return a;if(c){if(!N.kf(d.mode))return 54;if(N.wg(d)||N.If(d)===N.cwd())return 10}else if(N.kf(d.mode))return 31;return 0},zi:function(a,b){return a?
N.Mf(a.mode)?32:N.kf(a.mode)&&("r"!==N.th(b)||b&512)?31:N.Jf(a,N.th(b)):44},Qh:4096,Bi:function(a,b){b=b||N.Qh;for(a=a||0;a<=b;a++)if(!N.streams[a])return a;throw new N.af(33);},zf:function(a){return N.streams[a]},nh:function(a,b,c){N.Hg||(N.Hg=function(){},N.Hg.prototype={object:{get:function(){return this.node},set:function(g){this.node=g}}});var d=new N.Hg,e;for(e in a)d[e]=a[e];a=d;b=N.Bi(b,c);a.fd=b;return N.streams[b]=a},ai:function(a){N.streams[a]=null},$h:{open:function(a){a.df=N.ki(a.node.rdev).df;
a.df.open&&a.df.open(a)},tf:function(){throw new N.af(70);}},Wg:function(a){return a>>8},oj:function(a){return a&255},Of:function(a,b){return a<<8|b},dh:function(a,b){N.ph[a]={df:b}},ki:function(a){return N.ph[a]},wh:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.mg)}return b},Kh:function(a,b){function c(k){N.Cg--;return b(k)}function d(k){if(k){if(!d.gi)return d.gi=!0,c(k)}else++g>=e.length&&c(null)}"function"===typeof a&&(b=a,a=!1);N.Cg++;1<N.Cg&&h("warning: "+
N.Cg+" FS.syncfs operations in flight at once, probably just doing extra work");var e=N.wh(N.root.jf),g=0;e.forEach(function(k){if(!k.type.Kh)return d(null);k.type.Kh(k,a,d)})},jf:function(a,b,c){var d="/"===c,e=!c;if(d&&N.root)throw new N.af(10);if(!d&&!e){var g=N.ff(c,{Og:!1});c=g.path;g=g.node;if(N.Nf(g))throw new N.af(10);if(!N.kf(g.mode))throw new N.af(54);}b={type:a,tj:b,Eh:c,mg:[]};a=a.jf(b);a.jf=b;b.root=a;d?N.root=a:g&&(g.lg=b,g.jf&&g.jf.mg.push(b));return a},zj:function(a){a=N.ff(a,{Og:!1});
if(!N.Nf(a.node))throw new N.af(28);a=a.node;var b=a.lg,c=N.wh(b);Object.keys(N.Cf).forEach(function(d){for(d=N.Cf[d];d;){var e=d.Pf;-1!==c.indexOf(d.jf)&&N.Ng(d);d=e}});a.lg=null;a.jf.mg.splice(a.jf.mg.indexOf(b),1)},lookup:function(a,b){return a.cf.lookup(a,b)},Ff:function(a,b,c){var d=N.ff(a,{parent:!0}).node;a=Sb(a);if(!a||"."===a||".."===a)throw new N.af(28);var e=N.Yg(d,a);if(e)throw new N.af(e);if(!d.cf.Ff)throw new N.af(63);return d.cf.Ff(d,a,b,c)},create:function(a,b){return N.Ff(a,(void 0!==
b?b:438)&4095|32768,0)},mkdir:function(a,b){return N.Ff(a,(void 0!==b?b:511)&1023|16384,0)},qj:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{N.mkdir(c,b)}catch(e){if(20!=e.ef)throw e;}}},yg:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return N.Ff(a,b|8192,c)},symlink:function(a,b){if(!Vb(a))throw new N.af(44);var c=N.ff(b,{parent:!0}).node;if(!c)throw new N.af(44);b=Sb(b);var d=N.Yg(c,b);if(d)throw new N.af(d);if(!c.cf.symlink)throw new N.af(63);return c.cf.symlink(c,
b,a)},rename:function(a,b){var c=Rb(a),d=Rb(b),e=Sb(a),g=Sb(b);var k=N.ff(a,{parent:!0});var m=k.node;k=N.ff(b,{parent:!0});k=k.node;if(!m||!k)throw new N.af(44);if(m.jf!==k.jf)throw new N.af(75);var r=N.Bf(m,e);d=Wb(a,d);if("."!==d.charAt(0))throw new N.af(28);d=Wb(b,c);if("."!==d.charAt(0))throw new N.af(55);try{var q=N.Bf(k,g)}catch(t){}if(r!==q){c=N.kf(r.mode);if(e=N.xg(m,e,c))throw new N.af(e);if(e=q?N.xg(k,g,c):N.Yg(k,g))throw new N.af(e);if(!m.cf.rename)throw new N.af(63);if(N.Nf(r)||q&&N.Nf(q))throw new N.af(10);
if(k!==m&&(e=N.Jf(m,"w")))throw new N.af(e);try{N.mf.willMovePath&&N.mf.willMovePath(a,b)}catch(t){h("FS.trackingDelegate['willMovePath']('"+a+"', '"+b+"') threw an exception: "+t.message)}N.Ah(r);try{m.cf.rename(r,k,g)}catch(t){throw t;}finally{N.zh(r)}try{if(N.mf.onMovePath)N.mf.onMovePath(a,b)}catch(t){h("FS.trackingDelegate['onMovePath']('"+a+"', '"+b+"') threw an exception: "+t.message)}}},rmdir:function(a){var b=N.ff(a,{parent:!0}).node,c=Sb(a),d=N.Bf(b,c),e=N.xg(b,c,!0);if(e)throw new N.af(e);
if(!b.cf.rmdir)throw new N.af(63);if(N.Nf(d))throw new N.af(10);try{N.mf.willDeletePath&&N.mf.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.cf.rmdir(b,c);N.Ng(d);try{if(N.mf.onDeletePath)N.mf.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readdir:function(a){a=N.ff(a,{wf:!0}).node;if(!a.cf.readdir)throw new N.af(54);return a.cf.readdir(a)},unlink:function(a){var b=N.ff(a,
{parent:!0}).node,c=Sb(a),d=N.Bf(b,c),e=N.xg(b,c,!1);if(e)throw new N.af(e);if(!b.cf.unlink)throw new N.af(63);if(N.Nf(d))throw new N.af(10);try{N.mf.willDeletePath&&N.mf.willDeletePath(a)}catch(g){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.cf.unlink(b,c);N.Ng(d);try{if(N.mf.onDeletePath)N.mf.onDeletePath(a)}catch(g){h("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}},readlink:function(a){a=N.ff(a).node;if(!a)throw new N.af(44);
if(!a.cf.readlink)throw new N.af(28);return Vb(N.If(a.parent),a.cf.readlink(a))},stat:function(a,b){a=N.ff(a,{wf:!b}).node;if(!a)throw new N.af(44);if(!a.cf.Af)throw new N.af(63);return a.cf.Af(a)},lstat:function(a){return N.stat(a,!0)},chmod:function(a,b,c){var d;"string"===typeof a?d=N.ff(a,{wf:!c}).node:d=a;if(!d.cf.nf)throw new N.af(63);d.cf.nf(d,{mode:b&4095|d.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){N.chmod(a,b,!0)},fchmod:function(a,b){a=N.zf(a);if(!a)throw new N.af(8);N.chmod(a.node,
b)},chown:function(a,b,c,d){var e;"string"===typeof a?e=N.ff(a,{wf:!d}).node:e=a;if(!e.cf.nf)throw new N.af(63);e.cf.nf(e,{timestamp:Date.now()})},lchown:function(a,b,c){N.chown(a,b,c,!0)},fchown:function(a,b,c){a=N.zf(a);if(!a)throw new N.af(8);N.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new N.af(28);var c;"string"===typeof a?c=N.ff(a,{wf:!0}).node:c=a;if(!c.cf.nf)throw new N.af(63);if(N.kf(c.mode))throw new N.af(31);if(!N.isFile(c.mode))throw new N.af(28);if(a=N.Jf(c,"w"))throw new N.af(a);
c.cf.nf(c,{size:b,timestamp:Date.now()})},fj:function(a,b){a=N.zf(a);if(!a)throw new N.af(8);if(0===(a.flags&2097155))throw new N.af(28);N.truncate(a.node,b)},Aj:function(a,b,c){a=N.ff(a,{wf:!0}).node;a.cf.nf(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,e){if(""===a)throw new N.af(44);b="string"===typeof b?N.Dh(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Qb(a);try{g=N.ff(a,{wf:!(b&131072)}).node}catch(m){}}var k=!1;if(b&64)if(g){if(b&128)throw new N.af(20);
}else g=N.Ff(a,c,0),k=!0;if(!g)throw new N.af(44);N.hg(g.mode)&&(b&=-513);if(b&65536&&!N.kf(g.mode))throw new N.af(54);if(!k&&(c=N.zi(g,b)))throw new N.af(c);b&512&&N.truncate(g,0);b&=-131713;d=N.nh({node:g,path:N.If(g),flags:b,seekable:!0,position:0,df:g.df,Wi:[],error:!1},d,e);d.df.open&&d.df.open(d);!f.logReadFiles||b&1||(N.$g||(N.$g={}),a in N.$g||(N.$g[a]=1,h("FS.trackingDelegate error on read file: "+a)));try{N.mf.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=N.Mh.Gh.Rh),0!==(b&2097155)&&(e|=N.Mh.Gh.Sh),
N.mf.onOpenFile(a,e))}catch(m){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d},close:function(a){if(N.ig(a))throw new N.af(8);a.Lf&&(a.Lf=null);try{a.df.close&&a.df.close(a)}catch(b){throw b;}finally{N.ai(a.fd)}a.fd=null},ig:function(a){return null===a.fd},tf:function(a,b,c){if(N.ig(a))throw new N.af(8);if(!a.seekable||!a.df.tf)throw new N.af(70);if(0!=c&&1!=c&&2!=c)throw new N.af(28);a.position=a.df.tf(a,b,c);a.Wi=[];return a.position},read:function(a,
b,c,d,e){if(0>d||0>e)throw new N.af(28);if(N.ig(a))throw new N.af(8);if(1===(a.flags&2097155))throw new N.af(8);if(N.kf(a.node.mode))throw new N.af(31);if(!a.df.read)throw new N.af(28);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new N.af(70);b=a.df.read(a,b,c,d,e);g||(a.position+=b);return b},write:function(a,b,c,d,e,g){if(0>d||0>e)throw new N.af(28);if(N.ig(a))throw new N.af(8);if(0===(a.flags&2097155))throw new N.af(8);if(N.kf(a.node.mode))throw new N.af(31);if(!a.df.write)throw new N.af(28);
a.seekable&&a.flags&1024&&N.tf(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new N.af(70);b=a.df.write(a,b,c,d,e,g);k||(a.position+=b);try{if(a.path&&N.mf.onWriteToFile)N.mf.onWriteToFile(a.path)}catch(m){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+m.message)}return b},fg:function(a,b,c){if(N.ig(a))throw new N.af(8);if(0>b||0>=c)throw new N.af(28);if(0===(a.flags&2097155))throw new N.af(8);if(!N.isFile(a.node.mode)&&!N.kf(a.node.mode))throw new N.af(43);
if(!a.df.fg)throw new N.af(138);a.df.fg(a,b,c)},Wf:function(a,b,c,d,e,g){if(0!==(e&2)&&0===(g&2)&&2!==(a.flags&2097155))throw new N.af(2);if(1===(a.flags&2097155))throw new N.af(2);if(!a.df.Wf)throw new N.af(43);return a.df.Wf(a,b,c,d,e,g)},Xf:function(a,b,c,d,e){return a&&a.df.Xf?a.df.Xf(a,b,c,d,e):0},sj:function(){return 0},Uf:function(a,b,c){if(!a.df.Uf)throw new N.af(59);return a.df.Uf(a,b,c)},readFile:function(a,b){b=b||{};b.flags=b.flags||"r";b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&
"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=N.open(a,b.flags);a=N.stat(a).size;var e=new Uint8Array(a);N.read(d,e,0,a,0);"utf8"===b.encoding?c=Ja(e,0):"binary"===b.encoding&&(c=e);N.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||"w";a=N.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ma(b)+1);b=La(b,d,0,d.length);N.write(a,d,0,b,void 0,c.Zh)}else if(ArrayBuffer.isView(b))N.write(a,b,0,b.byteLength,void 0,c.Zh);else throw Error("Unsupported data type");
N.close(a)},cwd:function(){return N.oh},chdir:function(a){a=N.ff(a,{wf:!0});if(null===a.node)throw new N.af(44);if(!N.kf(a.node.mode))throw new N.af(54);var b=N.Jf(a.node,"x");if(b)throw new N.af(b);N.oh=a.path},ci:function(){N.mkdir("/tmp");N.mkdir("/home");N.mkdir("/home/web_user")},bi:function(){N.mkdir("/dev");N.dh(N.Of(1,3),{read:function(){return 0},write:function(b,c,d,e){return e}});N.yg("/dev/null",N.Of(1,3));Yb(N.Of(5,0),ac);Yb(N.Of(6,0),ec);N.yg("/dev/tty",N.Of(5,0));N.yg("/dev/tty1",N.Of(6,
0));var a=Ub();N.Hf("/dev","random",a);N.Hf("/dev","urandom",a);N.mkdir("/dev/shm");N.mkdir("/dev/shm/tmp")},ei:function(){N.mkdir("/proc");N.mkdir("/proc/self");N.mkdir("/proc/self/fd");N.jf({jf:function(){var a=N.createNode("/proc/self","fd",16895,73);a.cf={lookup:function(b,c){var d=N.zf(+c);if(!d)throw new N.af(8);b={parent:null,jf:{Eh:"fake"},cf:{readlink:function(){return d.path}}};return b.parent=b}};return a}},{},"/proc/self/fd")},fi:function(){f.stdin?N.Hf("/dev","stdin",f.stdin):N.symlink("/dev/tty",
"/dev/stdin");f.stdout?N.Hf("/dev","stdout",null,f.stdout):N.symlink("/dev/tty","/dev/stdout");f.stderr?N.Hf("/dev","stderr",null,f.stderr):N.symlink("/dev/tty1","/dev/stderr");N.open("/dev/stdin","r");N.open("/dev/stdout","w");N.open("/dev/stderr","w")},rh:function(){N.af||(N.af=function(a,b){this.node=b;this.Ki=function(c){this.ef=c};this.Ki(a);this.message="FS error"},N.af.prototype=Error(),N.af.prototype.constructor=N.af,[44].forEach(function(a){N.Qg[a]=new N.af(a);N.Qg[a].stack="<generic error, no stack>"}))},
Ni:function(){N.rh();N.Cf=Array(4096);N.jf(O,{},"/");N.ci();N.bi();N.ei();N.ii={MEMFS:O}},gg:function(a,b,c){N.gg.Tg=!0;N.rh();f.stdin=a||f.stdin;f.stdout=b||f.stdout;f.stderr=c||f.stderr;N.fi()},quit:function(){N.gg.Tg=!1;var a=f._fflush;a&&a(0);for(a=0;a<N.streams.length;a++){var b=N.streams[a];b&&N.close(b)}},Rg:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},ej:function(a,b){a=N.Lg(a,b);if(a.exists)return a.object;Fb(a.error);return null},Lg:function(a,b){try{var c=N.ff(a,{wf:!b});a=c.path}catch(e){}var d=
{wg:!1,exists:!1,error:0,name:null,path:null,object:null,Ci:!1,Ei:null,Di:null};try{c=N.ff(a,{parent:!0}),d.Ci=!0,d.Ei=c.path,d.Di=c.node,d.name=Sb(a),c=N.ff(a,{wf:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.wg="/"===c.path}catch(e){d.error=e.ef}return d},cj:function(a,b){a="string"===typeof a?a:N.If(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Tb(a,c);try{N.mkdir(d)}catch(e){}a=d}}return d},di:function(a,b,c,d,e){a=Tb("string"===typeof a?a:N.If(a),
b);return N.create(a,N.Rg(d,e))},mh:function(a,b,c,d,e,g){a=b?Tb("string"===typeof a?a:N.If(a),b):a;d=N.Rg(d,e);e=N.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}N.chmod(e,d|146);a=N.open(e,"w");N.write(a,c,0,c.length,0,g);N.close(a);N.chmod(e,d)}return e},Hf:function(a,b,c,d){a=Tb("string"===typeof a?a:N.If(a),b);b=N.Rg(!!c,!!d);N.Hf.Wg||(N.Hf.Wg=64);var e=N.Of(N.Hf.Wg++,0);N.dh(e,{open:function(g){g.seekable=!1},close:function(){d&&
d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,r){for(var q=0,t=0;t<r;t++){try{var w=c()}catch(B){throw new N.af(29);}if(void 0===w&&0===q)throw new N.af(6);if(null===w||void 0===w)break;q++;k[m+t]=w}q&&(g.node.timestamp=Date.now());return q},write:function(g,k,m,r){for(var q=0;q<r;q++)try{d(k[m+q])}catch(t){throw new N.af(29);}r&&(g.node.timestamp=Date.now());return q}});return N.yg(a,b,e)},uh:function(a){if(a.Ug||a.ti||a.link||a.bf)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)thr